eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://147.182.214.195:8799/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'routes,filters'

server:
  port: 8070
          
spring:
  application:
    name: servicio-zuul
    
zuul:
  ignored-headers:Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    socket-timeout-millis:40000
    connect-timeout-millis:40000

ribbon:
  ConnectTimeout:40000
  ReadTimeout:40000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    
zuul:
  #ignoredServices: '*'
  routes:
    personas:
      path: /servicio-personas/**
      serviceId: servicio-personas
      stripPrefix: false
      #url: http://localhost:2222/greeting/
    prueba:
      path: /prueba-microservice/**
      serviceId: prueba-microservice
      stripPrefix: false
      #url: http://localhost:2222/greeting/
